### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [braunemi/tea-cozy#6]
Superb job on this project - I really liked how you styled the nav, as well as how you chose to set up your copyright. In terms of improvement, I recommend adding an opacity to the images, creating a general flex-container to be used throughout the page, and using classes more when applicable. 

If you’re in the mood for a challenge, I would look into implementing a mobile version of this page! Here's a link to get you started: https://www.w3schools.com/css/css_rwd_mediaqueries.asp. Keep up the fantastic work! ^_^

**Comment by braunemi** [comment]
Thanks for your constructive criticism!
